Repository RumbleDB/rumble, pull requests merged in 2019-02, with the labels that each got.

#186 Fix serialize function.
  src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
Labels: Approved

#184 Lower memory footprint.
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/spark/closures/GroupByLinearizeTupleClosure.java
Labels: Approved

#180 Get rdd with context
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/RuntimeTupleIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParallelizeFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParseJsonFunctionIterator.java
Labels: Approved

#187 Orderby clause local
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
  src/main/java/sparksoniq/spark/closures/OrderByClauseSortClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal1.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal10.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal11.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal12.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal13.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal14.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal15.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal16.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal2.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal3.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal4.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal5.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal6.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal7.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal8.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocal9.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocalError1.iq
Labels: Approved, Changes Required

#190 Spark tests ordered
  src/main/resources/test_files/runtime-spark/EmptySequence2.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/LetClauseLocal1.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup2.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup3.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup4.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup5.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayUnboxing2.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup2.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup3.iq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookupNested.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Predicate.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Predicate2.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Predicate3.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Predicate4.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Predicate5.iq
  src/test/java/iq/SparkRuntimeTests.java
Labels: Merged - Closed

#188 Groupby clause local
  src/main/java/sparksoniq/spark/closures/GroupByToPairMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseLocal1.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseLocal2.iq
Labels: Approved
