Repository RumbleDB/rumble, pull requests merged in 2019-05, with the labels that each got.

#249 Fix dynamic context usage in groupby
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
Labels: Approved

#250 Spark exception message
  src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
Labels: Approved

#252 Object constructor
  src/main/java/sparksoniq/jsoniq/item/Item.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ObjectConstructorRuntimeIterator.java
  src/main/resources/test_files/runtime/ErrorNonStringKey.iq
Labels: Approved

#256 Fix keySet issue with older org.json.
  docs/Getting started.md
  docs/Run on a cluster.md
  docs/install.md
  pom.xml
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
Labels: Approved

#257 Distinct values rdd
  src/main/java/sparksoniq/jsoniq/item/ArrayItem.java
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/Item.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/SwitchRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/FilterNonAtomicClosure.java
  src/main/resources/test_files/runtime-spark/DistinctValues.iq
  src/main/resources/test_files/runtime-spark/DistinctValues2.iq
  src/main/resources/test_files/runtime-spark/DistinctValues3.iq
  src/main/resources/test_files/runtime-spark/DistinctValues4.iq
Labels: Approved, Review Required

#264 Clean up CLI.
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/Main.java
  src/main/java/sparksoniq/ShellStart.java
  src/main/java/sparksoniq/config/SparksoniqRuntimeConfiguration.java
  src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
Labels: Approved, enhancement

#263 Adjust handling of errors nested in Spark.
  src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
Labels: Approved, bug

#261 Cache intermediate view.
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
Labels: Approved, Dataframes, Development, enhancement, question

#265 Rumble rename
  README.md
  docs/Error codes.md
  docs/Function library.md
  docs/Getting started.md
  docs/JSONiq.md
  docs/Licenses.md
  docs/Run on a cluster.md
  docs/index.md
  docs/install.md
  pom.xml
  src/main/java/sparksoniq/Main.java
  src/main/resources/assets/banner.txt
Labels: Review Required
