Repository RumbleDB/rumble, pull requests merged in 2019-12, with the labels that each got.

#393 Add dataframe support to keys() function
  docs/Function library.md
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/resources/test_files/runtime-spark/Pushdown/KeysDF1.jq
  src/main/resources/test_files/runtime-spark/Pushdown/KeysDF2.jq
  src/main/resources/test_files/runtime-spark/Pushdown/KeysRDD.jq
  src/main/resources/test_files/runtime-spark/Pushdown/KeysRDD2.jq
Labels: Approved

#397 Fix bug with empty sequence in predicates or where clauses.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/WhereClause9.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate6.jq
Labels: Approved

#398 Use EBV in where clauses and predicates when pushing down to DF.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/WhereClause10.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate7.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate8.jq
Labels: Approved

#388 Improve iterators performances
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/TreatAsClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/InstanceOfIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/test/java/iq/RuntimeTests.java
Labels: Approved, enhancement

#399 Suggest bugfix.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TypePromotionIterator.java
Labels: Approved

#396 Version bump.
  docs/Getting started.md
  docs/JSONiq.md
  docs/Run on a cluster.md
  docs/install.md
  mkdocs.yml
  pom.xml
  src/main/resources/assets/banner.txt
Labels: Approved

#394 Fix order clause empty df handling
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/KeysDF3.jq
  src/main/resources/test_files/runtime-spark/Pushdown/KeysRDD3.jq
Labels: Approved

#400 Primitive types builtin functions
  docs/Error codes.md
  src/main/java/sparksoniq/exceptions/InvalidLexicalValueException.java
  src/main/java/sparksoniq/exceptions/StringOfJSONiqItemException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/DecimalFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/DoubleFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/IntegerFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StringFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctions.jq
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctionsError1.jq
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctionsError2.jq
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctionsError3.jq
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctionsError4.jq
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctionsError5.jq
  src/main/resources/test_files/runtime/FunctionString/StringFunctionError1.jq
  src/main/resources/test_files/runtime/FunctionString/StringFunctionError2.jq
  src/main/resources/test_files/runtime/FunctionString/StringFunctionError3.jq
  src/main/resources/test_files/runtime/FunctionString/stringFunction.jq
Labels: Approved, Language feature

#379 Group and order typechecked new types
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarDecl.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/ForClauseVar.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/LetClauseVar.java
  src/main/java/sparksoniq/jsoniq/item/Base64BinaryItem.java
  src/main/java/sparksoniq/jsoniq/item/DateItem.java
  src/main/java/sparksoniq/jsoniq/item/DateTimeItem.java
  src/main/java/sparksoniq/jsoniq/item/DayTimeDurationItem.java
  src/main/java/sparksoniq/jsoniq/item/DurationItem.java
  src/main/java/sparksoniq/jsoniq/item/HexBinaryItem.java
  src/main/java/sparksoniq/jsoniq/item/TimeItem.java
  src/main/java/sparksoniq/jsoniq/item/YearMonthDurationItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/DurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/GroupClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/ForClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroubyClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseBase64Binary.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseDate.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseDateTime.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseDurations.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseHexBinary.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClauseTime.jq
  src/main/resources/test_files/runtime-spark/DataFrames/LetClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseBase64Binary.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseDate.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseDateTime.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseDurations.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseError.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseHexBinary.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClauseTime.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/ForClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseBase64Binary.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseDate.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseDateTime.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseDurations.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseHexBinary.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseTime.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/GroupbyClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/LetClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderClauseLocalError1.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseBase64Binary.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseDate.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseDateTime.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseDurations.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseHexBinary.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/OrderbyClauseTime.jq
Labels: Approved, Language feature

#406 Fix contexts for passing outer variables.
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/WhereClause11.jq
  src/main/resources/test_files/runtime-spark/DataFrames/WhereClause8.jq
Labels: Approved

#408 Fix count optimization with let group
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause12.jq
Labels: Approved

#405 Typecheck user-defined functions
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TypePromotionIterator.java
  src/main/java/sparksoniq/semantics/types/SequenceType.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplication-Error2.jq
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplication-Error3.jq
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplicationRDD6.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD-Error1.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD-Error2.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD-Error3.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD-Error4.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD3.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD4.jq
  src/main/resources/test_files/runtime-spark/ParallelizePartitions-Error1.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/InlineFunctionDefinition-Error5.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/InlineFunctionDefinition-Error6.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/InlineFunctionDefinition-Error7.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/InlineFunctionDefinition4.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error14.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error15.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error16.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef3.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic-Error5.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic-Error6.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic-Error7.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic10.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic7.jq
Labels: Approved, enhancement

#411 Fix context chaining for FLWOR expression evaluation (DF-enabled nested in local)
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/ForClause7.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause13.jq
  src/main/resources/test_files/runtime-spark/DataFrames/LetClause3.jq
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClause6.jq
Labels: Approved

#407 Local and Spark Enabled Execution of Nested FLWOR Expressions
  docs/Error codes.md
  src/main/java/sparksoniq/exceptions/JobWithinAJobException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/DataFrames/ForClause8.jq
  src/main/resources/test_files/runtime-spark/DataFrames/ForClause9.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark1.jq.HOLD
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark2.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark3.jq.HOLD
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark4.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark5.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError1.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError2.jq
  src/main/resources/test_files/runtime-spark/ParallelizePartitions3.disabled
  src/main/resources/test_files/runtime-spark/ParallelizePartitions3.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication-Error2.jq
  src/main/resources/test_files/runtime/NestedFLWORLocal1.jq
  src/main/resources/test_files/runtime/NestedFLWORLocal2.jq
  src/main/resources/test_files/runtime/NestedFLWORLocal3.jq
  src/main/resources/test_files/runtime/NestedFLWORLocal4.jq
  src/test/java/iq/RuntimeTests.java
Labels: Approved, Changes Required, Dataframes, Language feature

#413 Throw appropriate errors for job within a job for all other clauses
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark1.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark1.jq.HOLD
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark2.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark3.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark3.jq.HOLD
  src/main/resources/test_files/runtime-spark/NestedFLWORSpark4.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError3.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError4.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError5.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError6.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError7.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError8.jq
Labels: Approved

#414 Support count optimization in other clauses.
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause14.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause15.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause16.jq
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause17.jq
Labels: Approved, bug, enhancement

#416 Add tests.
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/Recursion1.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/Recursion2.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/Recursion3.jq
Labels: Approved
