Repository RumbleDB/rumble, pull requests merged in 2019-11, with the labels that each got.

#353 Rdd execution support for function Items
  src/main/java/sparksoniq/jsoniq/item/FunctionItem.java
  src/main/java/sparksoniq/jsoniq/item/KryoManager.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/UserDefinedFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/FunctionIdentifier.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/semantics/types/ItemType.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD1.disabled
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD1.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD2.disabled
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD2.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/InlineFunctionDefinition3.jq
Labels: Approved

#356 DateTime type
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSequenceType.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSingleType.java
  src/main/java/sparksoniq/jsoniq/item/DateTimeItem.java
  src/main/java/sparksoniq/jsoniq/item/DayTimeDurationItem.java
  src/main/java/sparksoniq/jsoniq/item/DurationItem.java
  src/main/java/sparksoniq/jsoniq/item/ItemFactory.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/item/YearMonthDurationItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/DateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/base/BinaryOperationBaseIterator.java
  src/main/java/sparksoniq/semantics/types/AtomicTypes.java
  src/main/java/sparksoniq/semantics/types/ItemTypes.java
  src/main/resources/test_files/runtime/Cast.jq
  src/main/resources/test_files/runtime/Castable.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTime.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError2.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError3.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError4.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError5.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionDateTimeError6.jq
  src/main/resources/test_files/runtime/InstanceOf.jq
  src/main/resources/test_files/runtime/Operational/AdditiveOp5.jq
  src/main/resources/test_files/runtime/Operational/AdditiveOpError7.jq
  src/main/resources/test_files/runtime/Operational/Comparisons/GeneralComparisonDateTimes.jq
  src/main/resources/test_files/runtime/Operational/Comparisons/ValueComparisonDateTimes.jq
  src/main/resources/test_files/runtime/Treat.jq
Labels: Approved, Language feature

#352 Effective Boolean Value for new types throws error FORG0006
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/resources/test_files/runtime/FunctionBooleans/FunctionBooleanError4.jq
  src/main/resources/test_files/runtime/FunctionBooleans/FunctionBooleanError5.jq
Labels: Approved

#350 Implement partial application for local evaluation
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/primary/ArgumentPlaceholder.java
  src/main/java/sparksoniq/jsoniq/item/FunctionItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/UserDefinedFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/ComparisonOperationIterator.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplication-Error1.jq
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplicationRDD1.jq
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplicationRDD2.jq
  src/main/resources/test_files/runtime-spark/FunctionPartialApplication/PartialFunctionApplicationRDD3.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD-Error1.jq
  src/main/resources/test_files/runtime-spark/FunctionUserDefinedDynamic/NamedFunctionRefRDD3.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication-Error1.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication-Error2.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication1.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication2.jq
  src/main/resources/test_files/runtime/FunctionPartialApplication/PartialFunctionApplication3.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/DynamicFunctionCall-Error2.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error10.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error11.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error12.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error13.jq
  src/main/resources/test_files/runtime/FunctionUserDefinedDynamic/NamedFunctionRef-Error9.jq
Labels: Approved

#363 Extract fields from durations
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/DaysFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/HoursFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/MinutesFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/MonthsFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/SecondsFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/YearsFromDurationFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionDurations/ExtractingFieldsFromDurationError1.jq
  src/main/resources/test_files/runtime/FunctionDurations/ExtractingFieldsFromDurationError2.jq
  src/main/resources/test_files/runtime/FunctionDurations/ExtractingFieldsFromDurationError3.jq
  src/main/resources/test_files/runtime/FunctionDurations/ExtractingFieldsFromDurations.jq
Labels: Approved, Language feature

#364 Extract fields from date time
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/DayFromDateFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/DayFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/HoursFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/HoursFromTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/MinutesFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/MinutesFromTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/MonthFromDateFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/MonthFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/SecondsFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/SecondsFromTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/TimezoneFromDateFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/TimezoneFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/TimezoneFromTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/YearFromDateFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/YearFromDateTimeFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/DaysFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/HoursFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/MinutesFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/MonthsFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/SecondsFromDurationFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/components/YearsFromDurationFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionDateTimes/ExtractingFieldsFromDateTime.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/ExtractingFieldsFromDateTimeError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/ExtractingFieldsFromDateTimeError2.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/ExtractingFieldsFromDateTimeError3.jq
Labels: Approved, Language feature

#365 Adjust time zone
  src/main/java/sparksoniq/exceptions/InvalidTimezoneException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustDateTimeToTimezone.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustDateToTimezone.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/datetime/components/AdjustTimeToTimezone.java
  src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezone.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezoneError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/AdjustDateTimesToTimezoneError2.jq
Labels: Approved, Language feature

#357 Implement parser for Parquet.
  docs/Function library.md
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
  src/main/java/sparksoniq/io/json/RowToItemMapper.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/spark/iterator/function/ParquetFileFunctionIterator.java
  src/main/resources/queries/sample-json.snappy.parquet
  src/main/resources/test_files/runtime-spark/data-formats/parquet.jq
Labels: Approved

#348 Json doc
  docs/Error codes.md
  docs/Function library.md
  src/main/java/sparksoniq/exceptions/ErrorRetrievingResourceException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/io/JsonDocFunctionIterator.java
  src/main/resources/queries/SpreadOverMultipleLinesDocument.json
  src/main/resources/test_files/runtime/FunctionObject/FunctionJsonDoc.jq.deactivated
  src/main/resources/test_files/runtime/FunctionObject/FunctionJsonDocError1.jq
Labels: Approved, Function library, Language feature

#368 Release1.3
  docs/Getting started.md
  docs/Run on a cluster.md
  docs/index.md
  docs/install.md
  mkdocs.yml
  pom.xml
  src/main/resources/assets/banner.txt
Labels: Approved

#367 Refactor function catalog
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
Labels: Approved

#369 Position and Last (local and RDD)
  .gitignore
  docs/Error codes.md
  docs/Function library.md
  src/main/java/sparksoniq/exceptions/AbsentPartOfDynamicContextException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/context/LastFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/context/PositionFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/resources/test_files/runtime-spark/PositionPredicate1.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate2.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate3.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate5.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate6.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate7.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicate8.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicateError1.jq
  src/main/resources/test_files/runtime/PostFixPredicate/PostFixPredicateError2.jq
Labels: Review Required

#370 Allow numbers in predicates also on Spark.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateClosureZipped.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/resources/test_files/runtime-spark/PositionPredicate4.jq
  src/main/resources/test_files/runtime-spark/PositionPredicate5.jq
Labels: Review Required

#366 getDataFrame support for Hybrid RI
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/LocalRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/UserDefinedFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayUnboxingIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParallelizeFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParquetFileFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParseJsonFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/ParseTextFunctionIterator.java
Labels: Approved

#360 Hybrid treat as
  src/main/java/sparksoniq/jsoniq/item/DayTimeDurationItem.java
  src/main/java/sparksoniq/jsoniq/item/DurationItem.java
  src/main/java/sparksoniq/jsoniq/item/YearMonthDurationItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/InstanceOfClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/TreatAsClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/InstanceOfIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/main/resources/test_files/runtime-spark/FunctionSequence/RDDInstanceOf.jq
  src/main/resources/test_files/runtime-spark/FunctionSequence/RDDTreatAs.jq
  src/main/resources/test_files/runtime-spark/FunctionSequence/RDDTreatAsError.jq
  src/main/resources/test_files/runtime/InstanceOf.jq
  src/main/resources/test_files/runtime/InstanceOfBinaries.jq
  src/main/resources/test_files/runtime/InstanceOfDateTimes.jq
  src/main/resources/test_files/runtime/InstanceOfDurations.jq
  src/main/resources/test_files/runtime/InstanceOfWithEmptySequence.jq
  src/main/resources/test_files/runtime/InstanceOfWithNull.jq
Labels: Review Required, enhancement

#359 RDD version InstanceOf iterator
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/InstanceOfClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/InstanceOfIterator.java
Labels: Approved, enhancement

#374 Typeswitch expression
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/control/TypeSwitchCaseExpression.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/control/TypeSwitchExpression.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchCase.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchRuntimeIterator.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression1.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression2.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression3.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression4.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression5.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpressionError1.jq
Labels: Approved, Language feature

#376 Cleanup RDDs from TupleIterators, remove spark tuple iterator
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/RuntimeTupleIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKeyComparator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/java/sparksoniq/spark/closures/CountClauseClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
  src/main/java/sparksoniq/spark/closures/GroupByLinearizeTupleClosure.java
  src/main/java/sparksoniq/spark/closures/GroupByToPairMapClosure.java
  src/main/java/sparksoniq/spark/closures/InitialForClauseClosure.java
  src/main/java/sparksoniq/spark/closures/LetClauseMapClosure.java
  src/main/java/sparksoniq/spark/closures/OLD_ForClauseLocalToRDDClosure.java
  src/main/java/sparksoniq/spark/closures/OLD_LetClauseMapClosure.java
  src/main/java/sparksoniq/spark/closures/OLD_WhereClauseClosure.java
  src/main/java/sparksoniq/spark/closures/OrderByMapToPairClosure.java
  src/main/java/sparksoniq/spark/closures/WhereClauseMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
Labels: Approved

#378 Improve naming for User defined function call classes
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/StaticUserDefinedFunctionCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
Labels: Approved

#380 Make sure that only one grouping key is taken when keys in the same group are different.
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause11.jq
Labels: Approved

#375 Add RDD support to FLWOR tuple
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/Main.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
Labels: Approved

#384 Fix test.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
Labels: Approved

#382 Support initial let clause RDDs and DFs without instant materialization
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ContextExpressionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
Labels: Approved

#386 Structured json file
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/spark/iterator/function/JsonFileFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/StructuredJsonFileFunctionIterator.java
  src/main/java/sparksoniq/spark/iterator/function/TextFileFunctionIterator.java
  src/main/resources/queries/emptyFile.json
  src/main/resources/queries/emptyFile.txt
  src/main/resources/test_files/runtime-spark/FileInputs/JsonFile.jq
  src/main/resources/test_files/runtime-spark/FileInputs/JsonFileEmpty.jq
  src/main/resources/test_files/runtime-spark/FileInputs/Parquet.jq
  src/main/resources/test_files/runtime-spark/FileInputs/ParquetEmpty.jq.disabled
  src/main/resources/test_files/runtime-spark/FileInputs/StructuredJsonFile.jq
  src/main/resources/test_files/runtime-spark/FileInputs/StructuredJsonFileEmpty.jq
  src/main/resources/test_files/runtime-spark/FileInputs/StructuredJsonFileError.jq
  src/main/resources/test_files/runtime-spark/FileInputs/TextFile.jq
  src/main/resources/test_files/runtime-spark/FileInputs/TextFile2.jq
  src/main/resources/test_files/runtime-spark/FileInputs/TextFileEmpty.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionExactlyOneRDDError1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMoreRDDError1.disabled
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionZeroOrOneRDD1.jq
Labels: Approved

#387 Start renaming packages and deprecated ShellStart.
  pom.xml
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/org/rumbledb/cli/ShellStart.java
  src/main/java/org/rumbledb/config/SparksoniqRuntimeConfiguration.java
  src/main/java/sparksoniq/io/shell/JiqsJLineShell.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/java/sparksoniq/utils/FileUtils.java
Labels: Approved

#391 Edit MainClass path
  pom.xml
Labels: Review Required, bug

#390 Throw UnknownFunctionCallException if non-existing function is called
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/resources/test_files/runtime/FunctionUserDefinedStatic/FunctionUserDefinedStatic-Error4.jq
Labels: Approved, bug

#392 Add count calculation for DF
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
  src/main/resources/test_files/runtime-spark/FunctionSequence/FunctionCountDF.jq
  src/main/resources/test_files/runtime-spark/FunctionSequence/FunctionCountRDD.jq
Labels: Approved, Changes Required
