Repository RumbleDB/rumble, pull requests merged in 2019-10, with the labels that each got.

#323 Instance of operator
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSequenceType.java
  src/main/java/sparksoniq/jsoniq/item/ArrayItem.java
  src/main/java/sparksoniq/jsoniq/item/AtomicItem.java
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/JsonItem.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/InstanceOfIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/UnaryOperationIterator.java
  src/main/java/sparksoniq/semantics/types/SequenceType.java
  src/main/resources/test_files/runtime/InstanceOf.jq
  src/main/resources/test_files/runtime/Operational/UnaryOp.jq
Labels: Language feature, Review Required

#324 Treat as operator
  src/main/java/sparksoniq/exceptions/TreatException.java
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/TreatExpression.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/main/java/sparksoniq/semantics/types/ItemTypes.java
  src/main/java/sparksoniq/semantics/types/SequenceType.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/resources/test_files/runtime/Treat.jq
  src/main/resources/test_files/runtime/TreatError1.jq
  src/main/resources/test_files/runtime/TreatError2.jq
  src/main/resources/test_files/runtime/TreatError3.jq
  src/main/resources/test_files/runtime/TreatError4.jq
  src/main/resources/test_files/runtime/TreatError5.jq
  src/main/resources/test_files/runtime/TreatError6.jq
  src/main/resources/test_files/runtime/TreatError7.jq
  src/main/resources/test_files/runtime/TreatError8.jq
  src/main/resources/test_files/runtime/TreatError9.jq
Labels: Approved, Language feature

#325 Castable as operator
  src/main/java/sparksoniq/exceptions/CastableException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSingleType.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/CastableExpression.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
  src/main/java/sparksoniq/jsoniq/item/AtomicItem.java
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/ObjectItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastableIterator.java
  src/main/java/sparksoniq/semantics/types/AtomicTypes.java
  src/main/java/sparksoniq/semantics/types/SingleType.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/resources/test_files/runtime/Castable.jq
  src/main/resources/test_files/runtime/CastableError1.jq
  src/main/resources/test_files/runtime/CastableError2.jq
  src/main/resources/test_files/runtime/CastableError3.jq
Labels: Approved, Language feature

#327 Substring before
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/SubstringBeforeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/SubstringBefore.jq
Labels: Approved, Function library

#328 Substring after
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/SubstringAfterFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/SubstringAfter.jq
Labels: Approved, Function library

#326 Cast as operator
  docs/JSONiq.md
  src/main/java/sparksoniq/exceptions/CastException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/CastExpression.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
  src/main/java/sparksoniq/jsoniq/item/AtomicItem.java
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastableIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/TreatIterator.java
  src/main/java/sparksoniq/semantics/types/SingleType.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/resources/test_files/runtime/Cast.jq
  src/main/resources/test_files/runtime/CastError1.jq
  src/main/resources/test_files/runtime/CastError2.jq
  src/main/resources/test_files/runtime/CastError3.jq
Labels: Approved, Language feature

#330 Add caching to travis build
  .travis.yml
Labels: Approved

#331 Reformat grammar
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
Labels: Approved

#332 Fix grammar file typo for switch cases
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
Labels: Review Required

#333 Standardize variables in .g4, fix 'fcnName' typo
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
Labels: Review Required

#334 HybridRuntimeIterator - openLocal() simplified
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DistinctValuesFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayUnboxingIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ObjectLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
Labels: Approved

#329 Change how item comparison is performed
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/operational/base/OperationalExpressionBase.java
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/ComparisonOperationIterator.java
Labels: Refactoring, Review Required, enhancement

#338 Hex binary type
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSequenceType.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSingleType.java
  src/main/java/sparksoniq/jsoniq/item/HexBinaryItem.java
  src/main/java/sparksoniq/jsoniq/item/ItemFactory.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/binaries/HexBinaryFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/CastIterator.java
  src/main/java/sparksoniq/semantics/types/AtomicTypes.java
  src/main/java/sparksoniq/semantics/types/ItemTypes.java
  src/main/resources/test_files/runtime/Cast.jq
  src/main/resources/test_files/runtime/Castable.jq
  src/main/resources/test_files/runtime/FunctionBinaries/FunctionHexBinary.jq
  src/main/resources/test_files/runtime/FunctionBinaries/FunctionHexBinaryError1.jq
  src/main/resources/test_files/runtime/FunctionBinaries/FunctionHexBinaryError2.jq
  src/main/resources/test_files/runtime/FunctionBinaries/FunctionHexBinaryError3.jq
  src/main/resources/test_files/runtime/FunctionBinaries/FuntionHexBinaryError4.jq
  src/main/resources/test_files/runtime/InstanceOf.jq
  src/main/resources/test_files/runtime/Treat.jq
Labels: Approved, Changes Required, Language feature

#337 Change how arithmetic operations are performed
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/AdditiveOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/MultiplicativeOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/base/BinaryOperationBaseIterator.java
  src/main/java/sparksoniq/semantics/types/ItemTypes.java
  src/main/resources/test_files/runtime-spark/DataFrames/OrderbyClause5.jq
  src/main/resources/test_files/runtime/Cast.jq
  src/main/resources/test_files/runtime/CommaExpression1.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionExp.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionExp10.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionLog.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionLog10.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionPow1.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Exponential/FunctionSqrt.jq
  src/main/resources/test_files/runtime/FunctionNumerics/FunctionCeiling.jq
  src/main/resources/test_files/runtime/FunctionNumerics/FunctionFloor.jq
  src/main/resources/test_files/runtime/FunctionNumerics/FunctionRound1.jq
  src/main/resources/test_files/runtime/FunctionNumerics/FunctionRoundHalfToEven1.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionACos.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionASin.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionATan.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionATan2.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionCos.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionSin.jq
  src/main/resources/test_files/runtime/FunctionNumerics/Trigonometric/FunctionTan.jq
  src/main/resources/test_files/runtime/FunctionObject/FunctionObjectAccumulate1.jq
  src/main/resources/test_files/runtime/FunctionObject/FunctionObjectAccumulate5.jq
  src/main/resources/test_files/runtime/FunctionObject/FunctionObjectIntersect5.jq
  src/main/resources/test_files/runtime/FunctionObject/FunctionObjectValues3.jq
  src/main/resources/test_files/runtime/FunctionSequence/Aggregate/AggregateAverage1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Aggregate/AggregateMax1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Aggregate/AggregateMin1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Aggregate/AggregateSum1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Aggregate/FunctionAggregate.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionExactlyOne1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMore1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionZeroOrOne1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDistinctValues1.jq
  src/main/resources/test_files/runtime/FunctionString/ConcatFunction2.jq
  src/main/resources/test_files/runtime/Operational/AdditiveOp2.jq
  src/main/resources/test_files/runtime/Operational/AdditiveOp3.jq
  src/main/resources/test_files/runtime/Operational/AdditiveOpError2.jq
  src/main/resources/test_files/runtime/Operational/MultiplicativeOp2.jq
  src/main/resources/test_files/runtime/Operational/MultiplicativeOp3.jq
  src/main/resources/test_files/runtime/Operational/MultiplicativeOp5.jq
  src/main/resources/test_files/runtime/Operational/MultiplicativeOpError2.jq
  src/main/resources/test_files/runtime/Operational/StringConcat2.jq
Labels: Approved, enhancement

#341 Release Rumble 1.2
  docs/Getting started.md
  docs/Run on a cluster.md
  docs/install.md
  mkdocs.yml
  pom.xml
  src/main/resources/assets/banner.txt
Labels: Approved

#336 Duration type
  LICENSE-Joda-time.txt
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.g4
  src/main/java/sparksoniq/jsoniq/compiler/parser/Jsoniq.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.tokens
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSequenceType.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworVarSingleType.java
  src/main/java/sparksoniq/jsoniq/item/DurationItem.java
  src/main/java/sparksoniq/jsoniq/item/ItemFactory.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/durations/DurationFunctionIterator.java
  src/main/java/sparksoniq/semantics/types/AtomicTypes.java
  src/main/java/sparksoniq/semantics/types/ItemTypes.java
  src/main/resources/test_files/runtime/Cast.jq
  src/main/resources/test_files/runtime/Castable.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDuration.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError1.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError10.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError11.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError12.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError2.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError3.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError4.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError5.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError6.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError7.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError8.jq
  src/main/resources/test_files/runtime/FunctionDurations/FunctionDurationError9.jq
  src/main/resources/test_files/runtime/InstanceOf.jq
  src/main/resources/test_files/runtime/Operational/Comparisons/ErrorValueComparisonDurationType.jq
  src/main/resources/test_files/runtime/Operational/Comparisons/GeneralComparisonDurations.jq
  src/main/resources/test_files/runtime/Operational/Comparisons/ValueComparisonDurations.jq
  src/main/resources/test_files/runtime/Treat.jq
Labels: Language feature

#344 Release1.2
  docs/Getting started.md
  docs/Run on a cluster.md
  docs/install.md
  mkdocs.yml
  pom.xml
  src/main/resources/assets/banner.txt
Labels: Approved
