Repository RumbleDB/rumble, pull requests merged in 2019-03, with the labels that each got.

#191 Count clause local
  src/main/java/sparksoniq/spark/SparkContextManager.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/base/FlowrClauseSparkIterator.java
  src/main/resources/test_files/runtime-spark/LocalClauses/CountClauseLocal1.iq
  src/main/resources/test_files/runtime-spark/LocalClauses/CountClauseLocal2.iq
  src/test/java/utils/SequenceStringComparator.java
Labels: Approved

#173 Update documentation towards 0.9.5
  docs/Function library.md
  docs/Getting started.md
  docs/JSONiq.md
  docs/Run on a cluster.md
  docs/install.md
  pom.xml
Labels: Review Required

#195 Update documentation
  docs/JSONiq.md
Labels: Review Required

#196 Attempt another migration to ANTLR 4.7.
  pom.xml
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqBaseVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqLexer.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqParser.java
  src/main/java/sparksoniq/jsoniq/compiler/parser/JsoniqVisitor.java
Labels: Approved

#198 Suppressing security issue message
  pom.xml
Labels: Approved

#200 Fix for clause dynamic context usage.
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/SparkRuntimeTupleIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
Labels: Approved

#201 Improve code organization and styling for testing
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/resources/test_files/runtime/JsoniqVersion.iq
  src/test/java/iq/RuntimeTests.java
  src/test/java/iq/SparkRuntimeTests.java
  src/test/java/iq/base/AnnotationsTestsBase.java
Labels: Merged - Closed

#206 Fix bug to make sure the local query is read from the file provided w…
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/Main.java
Labels: Merged - Closed

#208 Local clause cleanup
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
Labels: Approved

#212 Local query logging
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/Main.java
  src/main/java/sparksoniq/ShellStart.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
Labels: Approved
