Repository RumbleDB/rumble, pull requests merged in 2019-06, with the labels that each got.

#273 Add Kryo license
  LICENSE-Kryo.md
Labels: Review Required

#274 Keys and values pushdown
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectKeysFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesClosure.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectValuesFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/Keys.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Values.iq
Labels: Approved

#272 Cache intermediate DF in group by
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
Labels: Approved, Dataframes, Development, enhancement, question

#270 Implement starts-with
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StartsWithFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/StartsWith1.iq
Labels: Approved, Function library, enhancement

#276 Ends with
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/EndsWithFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/EndsWith.iq
Labels: Approved, Function library

#268 Cleanup return clause's getRdd()
  src/main/java/sparksoniq/spark/closures/OLD_ReturnFlatMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
Labels: Approved, Dataframes

#279 Empty/Exists/Head pushdown
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/EmptyFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/ExistsFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/HeadFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/Exists.iq
  src/main/resources/test_files/runtime-spark/Pushdown/Head.iq
  src/main/resources/test_files/runtime-spark/Pushdown/IsEmpty.iq
Labels: Approved, Function library

#277 Implement contains().
  docs/Function library.md
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/ContainsFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/Contains.iq
Labels: Approved, Changes Required, Function library

#275 Variable dependencies
  src/main/java/sparksoniq/JsoniqQueryExecutor.java
  src/main/java/sparksoniq/config/SparksoniqRuntimeConfiguration.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/primary/VariableReference.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ContextExpressionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/tupleiterator/RuntimeTupleIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
Labels: Approved

#287 Non buffered output
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/ExistsFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DeepEqualFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/EndsWithFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StartsWithFunctionIterator.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
  src/main/java/sparksoniq/spark/udf/CountClauseSerializeUDF.java
  src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseSerializeAggregateResultsUDF.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
Labels: Approved, Dataframes
