Repository RumbleDB/rumble, pull requests merged in 2019-07, with the labels that each got.

#288 Upgrade Kryo and deactivate references.
  pom.xml
  src/main/java/sparksoniq/Main.java
  src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
  src/main/java/sparksoniq/spark/closures/LetClauseMapClosure.java
  src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
  src/main/java/sparksoniq/spark/closures/WhereClauseMapClosure.java
  src/main/java/sparksoniq/spark/udf/CountClauseSerializeUDF.java
  src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/GroupClauseSerializeAggregateResultsUDF.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
Labels: Approved, Dataframes

#285 Variable dependencies data frames
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/closures/ForClauseLocalToRowClosure.java
  src/main/java/sparksoniq/spark/closures/ForClauseSerializeClosure.java
  src/main/java/sparksoniq/spark/closures/ReturnFlatMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/CountClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/WhereClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/ForClauseUDF.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/main/java/sparksoniq/spark/udf/WhereClauseUDF.java
Labels: Approved, Changes Required, Development

#290 More informative output in case of general error.
  src/main/java/sparksoniq/Main.java
Labels: Approved

#289 Serialization pool
  src/main/java/sparksoniq/spark/DataFrameUtils.java
Labels: Approved, Dataframes

#292 Switch to a faster iterator-based JSON parser
  LICENSE-Jsoniter.txt
  pom.xml
  src/main/java/sparksoniq/Main.java
  src/main/java/sparksoniq/io/json/JiqsItemParser.java
  src/main/java/sparksoniq/io/json/StringToItemMapper.java
  src/main/java/sparksoniq/spark/closures/ForClauseFlatMapClosure.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/udf/LetClauseUDF.java
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause1.iq
  src/main/resources/test_files/runtime-spark/ForWhereOrderBy.iq
  src/main/resources/test_files/runtime-spark/JsonFile.iq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionExactlyOneRDD1.iq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionZeroOrOneRDD1.iq
Labels: Approved, enhancement

#294 Refactor static methods of Item class
  src/main/java/sparksoniq/jsoniq/item/BooleanItem.java
  src/main/java/sparksoniq/jsoniq/item/DecimalItem.java
  src/main/java/sparksoniq/jsoniq/item/DoubleItem.java
  src/main/java/sparksoniq/jsoniq/item/IntegerItem.java
  src/main/java/sparksoniq/jsoniq/item/Item.java
  src/main/java/sparksoniq/jsoniq/item/ItemComparatorForSequences.java
  src/main/java/sparksoniq/jsoniq/item/JsonItem.java
  src/main/java/sparksoniq/jsoniq/item/NullItem.java
  src/main/java/sparksoniq/jsoniq/item/StringItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/AbsFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/CeilingFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/FloorFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/RoundFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/RoundHalfToEvenFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/Exp10FunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/ExpFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/Log10FunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/LogFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/PowFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/exponential/SqrtFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/ACosFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/ASinFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/ATan2FunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/ATanFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/CosFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/SinFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/numerics/trigonometric/TanFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/AvgFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/SumFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/SubsequenceFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/IndexOfFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/AdditiveOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/ComparisonOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/MultiplicativeOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/RangeOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/UnaryOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/ArrayLookupIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
Labels: Approved, enhancement
