Repository RumbleDB/rumble, pull requests merged in 2020-03, with the labels that each got.

#491 Brp2 dev test
  docs/Function library.md
  src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
  src/main/java/org/rumbledb/exceptions/InvalidReplacementStringException.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/strings/ReplaceFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/CodepointEqual1.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointEqual2.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointsToString1.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointsToString2.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointsToStringError1.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointsToStringError2.jq
  src/main/resources/test_files/runtime/FunctionString/CodepointsToStringError3.jq
  src/main/resources/test_files/runtime/FunctionString/LowerCase1.jq
  src/main/resources/test_files/runtime/FunctionString/LowerCase2.jq
  src/main/resources/test_files/runtime/FunctionString/Replace1.jq
  src/main/resources/test_files/runtime/FunctionString/Replace2.jq
  src/main/resources/test_files/runtime/FunctionString/ReplaceError1.jq
  src/main/resources/test_files/runtime/FunctionString/ReplaceError2.jq
  src/main/resources/test_files/runtime/FunctionString/ReplaceError3.jq
  src/main/resources/test_files/runtime/FunctionString/ReplaceError4.jq
  src/main/resources/test_files/runtime/FunctionString/StringToCodepoints1.jq
  src/main/resources/test_files/runtime/FunctionString/StringToCodepoints2.jq
  src/main/resources/test_files/runtime/FunctionString/Translate1.jq
  src/main/resources/test_files/runtime/FunctionString/Translate2.jq
  src/main/resources/test_files/runtime/FunctionString/UpperCase.jq
  src/main/resources/test_files/runtime/FunctionString/UpperCase1.jq
  src/main/resources/test_files/runtime/FunctionString/UpperCase2.jq
Labels: Approved

#492 Implemented 'number' function
  docs/Function library.md
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/numerics/NumberFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionNumerics/NumericFunctions.jq
Labels: Approved

#493 Fix vector parsing in itemParser, add logistic regression tests
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/resources/queries/rumbleML/sample-libsvm-data-short.txt
  src/main/resources/test_files/runtime-spark/RumbleML/MLEstimator-Error-FeaturesCol1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLEstimator-Error-FeaturesCol2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLEstimator-KMeans1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLEstimator-LogisticRegression1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Error-IllegalArgument1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Error-IllegalArgument2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Multiple1.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Tokenizer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-VectorAssembler1.jq
Labels: Approved

#479 Clean up expression tree (eliminate duplicate sequence type classes).
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/control/TypeSwitchExpression.java
  src/main/java/org/rumbledb/expressions/control/TypeswitchCase.java
  src/main/java/org/rumbledb/expressions/flowr/FlworVarDecl.java
  src/main/java/org/rumbledb/expressions/flowr/FlworVarSequenceType.java
  src/main/java/org/rumbledb/expressions/flowr/ForClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/LetClauseVar.java
  src/main/java/org/rumbledb/expressions/operational/InstanceOfExpression.java
  src/main/java/org/rumbledb/expressions/operational/TreatExpression.java
  src/main/java/org/rumbledb/expressions/primary/InlineFunctionExpression.java
  src/main/java/org/rumbledb/runtime/control/TypeswitchRuntimeIterator.java
  src/main/java/org/rumbledb/runtime/control/TypeswitchRuntimeIteratorCase.java
  src/main/java/org/rumbledb/runtime/operational/InstanceOfIterator.java
  src/main/java/org/rumbledb/runtime/operational/TreatIterator.java
  src/main/java/sparksoniq/semantics/types/ItemType.java
  src/main/java/sparksoniq/semantics/types/SequenceType.java
Labels: Approved

#496 Cleanup ml catalog's getter/validator methods
  src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
Labels: Approved

#471 Implement (annotate(object*, object) as object*) function: Local/RDD -> DataFrame conversion with schema
  docs/Error codes.md
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
  src/main/java/org/rumbledb/exceptions/MLInvalidDataFrameSchemaException.java
  src/main/java/org/rumbledb/exceptions/MLNotADataFrameException.java
  src/main/java/org/rumbledb/expressions/operational/TreatExpression.java
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/sparksoniq/semantics/types/ItemType.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/ml/AnnotateFunctionIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes2.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-SchemaError4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-Transformer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Estimator-Error1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Transformer-Error1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Transformer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Multiple1.jq.disabled
Labels: Approved

#480 Start of research project 1: implementation of functions related to current date and time.
  .github/CODEOWNERS
  docs/Function library.md
  src/main/java/org/rumbledb/items/DateItem.java
  src/main/java/org/rumbledb/items/DateTimeItem.java
  src/main/java/org/rumbledb/items/TimeItem.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentDateFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentDateTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentTimeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTime.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTimeError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTimeError2.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDate.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDateError1.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDateError2.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTime.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTimeError1.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTimeError2.jq
Labels: Approved

#497 Flatten hierarchy.
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/operational/CastableExpression.java
  src/main/java/org/rumbledb/expressions/operational/base/OperationalExpressionBase.java
  src/main/java/org/rumbledb/expressions/primary/ArrayConstructorExpression.java
  src/main/java/org/rumbledb/expressions/primary/BooleanLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/ContextItemExpression.java
  src/main/java/org/rumbledb/expressions/primary/DecimalLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/DoubleLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/FunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/primary/InlineFunctionExpression.java
  src/main/java/org/rumbledb/expressions/primary/IntegerLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/NamedFunctionReferenceExpression.java
  src/main/java/org/rumbledb/expressions/primary/NullLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/ObjectConstructorExpression.java
  src/main/java/org/rumbledb/expressions/primary/PrimaryExpression.java
  src/main/java/org/rumbledb/expressions/primary/StringLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/VariableReferenceExpression.java
  src/main/java/org/rumbledb/runtime/operational/CastableIterator.java
  src/main/java/sparksoniq/jsoniq/compiler/ValueTypeHandler.java
Labels: Approved

#495 Changed arity of filepath string parameter of all input functions to 'required'
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
Labels: Approved

#502 RumbleML: Implement Feature Vector Generation with FeaturesCol param
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
  src/main/resources/queries/rumbleML/sample-libsvm-data-kmeans.txt
  src/main/resources/queries/rumbleML/sample-ml-data-age-weight.json
  src/main/resources/queries/rumbleML/sample-ml-data-numeric-array.json
  src/main/resources/queries/rumbleML/sample-ml-data-sentence.json
  src/main/resources/queries/rumbleML/sample-ml-numeric-array-data.json
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForChaining1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForChaining10.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForChaining2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForChaining3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForEstimator1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForTransformer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForTransformer2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal-SchemaError1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal-SchemaError2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal-SchemaError3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal-SchemaError4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal-SchemaError5.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateLocal3.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-KMeans1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-LogisticRegression1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/FeatureVectorization/MLFeatureVectorization-Error1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/FeatureVectorization/MLFeatureVectorization-Error2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/FeatureVectorization/MLFeatureVectorization-Error3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/FeatureVectorization/MLFeatureVectorization1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/FeatureVectorization/MLFeatureVectorization2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-AtomicTypes2.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateLocal-Transformer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLAnnotateRDD-Transformer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLEstimator-KMeans1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLNonDF-Error1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLNonDF-Error2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLParamError1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLParamError2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLParamError3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLParamError4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformer-Multiple1.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Binarizer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Tokenizer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-VectorAssembler1.jq
Labels: Approved

#503 Implemented csv-file function
  docs/Function library.md
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/input/CSVFileFunctionIterator.java
  src/main/resources/queries/cities-ex.csv
  src/main/resources/queries/cities.csv
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFile1.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFile2.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFileEmpty.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFileError.jq
Labels: Approved

#506 Bringing up to spec so that boolean() has the expected behaviour
  src/main/java/org/rumbledb/runtime/RuntimeIterator.java
Labels: Approved

#509 Bypass comma expression
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
Labels: Approved

#505 Annotate() function: type checking for dataframes
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/ml/AnnotateFunctionIterator.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF-SchemaError1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF-SchemaError2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF-SchemaError3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF-SchemaError4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateDF2.jq
Labels: Approved

#514 Improve annotate() and DataFrameUtils exceptions
  src/main/java/org/rumbledb/exceptions/MLInvalidDataFrameSchemaException.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/ml/AnnotateFunctionIterator.java
Labels: Approved

#510 Implemented anyURI atomic type with corresonding constructor
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/org/rumbledb/items/AnyURIItem.java
  src/main/java/org/rumbledb/items/ItemFactory.java
  src/main/java/org/rumbledb/items/StringItem.java
  src/main/java/org/rumbledb/parser/Jsoniq.g4
  src/main/java/org/rumbledb/parser/Jsoniq.tokens
  src/main/java/org/rumbledb/parser/JsoniqBaseVisitor.java
  src/main/java/org/rumbledb/parser/JsoniqLexer.java
  src/main/java/org/rumbledb/parser/JsoniqLexer.tokens
  src/main/java/org/rumbledb/parser/JsoniqParser.java
  src/main/java/org/rumbledb/parser/JsoniqVisitor.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/resources/AnyURIFunctionIterator.java
  src/main/java/org/rumbledb/types/ItemType.java
  src/main/java/org/rumbledb/types/ItemTypes.java
  src/main/resources/test_files/runtime/CastAnyURIs.jq
  src/main/resources/test_files/runtime/CastableAnyURI.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURI.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURIError1.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURIError2.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURIError3.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURIError4.jq
  src/main/resources/test_files/runtime/FunctionBooleans/FunctionBoolean3.jq
  src/main/resources/test_files/runtime/InstanceOfAnyURI.jq
  src/main/resources/test_files/runtime/Treat.jq
Labels: Approved

#512 Implemented csv-file options argument
  docs/Function library.md
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/input/CSVFileFunctionIterator.java
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFile3.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFile4.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFileError1.jq
  src/main/resources/test_files/runtime-spark/FileInputs/CsvFileError2.jq
Labels: Approved

#507 Item types encapsulation
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/items/ArrayItem.java
  src/main/java/org/rumbledb/items/AtomicItem.java
  src/main/java/org/rumbledb/items/Base64BinaryItem.java
  src/main/java/org/rumbledb/items/BooleanItem.java
  src/main/java/org/rumbledb/items/DateItem.java
  src/main/java/org/rumbledb/items/DateTimeItem.java
  src/main/java/org/rumbledb/items/DayTimeDurationItem.java
  src/main/java/org/rumbledb/items/DecimalItem.java
  src/main/java/org/rumbledb/items/DoubleItem.java
  src/main/java/org/rumbledb/items/DurationItem.java
  src/main/java/org/rumbledb/items/FunctionItem.java
  src/main/java/org/rumbledb/items/HexBinaryItem.java
  src/main/java/org/rumbledb/items/IntegerItem.java
  src/main/java/org/rumbledb/items/JsonItem.java
  src/main/java/org/rumbledb/items/NullItem.java
  src/main/java/org/rumbledb/items/ObjectItem.java
  src/main/java/org/rumbledb/items/StringItem.java
  src/main/java/org/rumbledb/items/TimeItem.java
  src/main/java/org/rumbledb/items/YearMonthDurationItem.java
  src/main/java/org/rumbledb/runtime/RuntimeIterator.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/OrderByClauseSparkIterator.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/OrderClauseCreateColumnsUDF.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/OrderClauseDetermineTypeUDF.java
  src/main/java/org/rumbledb/runtime/functions/durations/DayTimeDurationFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/durations/DurationFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/durations/YearMonthDurationFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/numerics/DecimalFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/numerics/DoubleFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/numerics/IntegerFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/TreatAsClosure.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/TypePromotionClosure.java
  src/main/java/org/rumbledb/runtime/functions/strings/StringFunctionIterator.java
  src/main/java/org/rumbledb/runtime/operational/AdditiveOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/CastIterator.java
  src/main/java/org/rumbledb/runtime/operational/CastableIterator.java
  src/main/java/org/rumbledb/runtime/operational/MultiplicativeOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/TreatIterator.java
  src/main/java/org/rumbledb/runtime/operational/TypePromotionIterator.java
  src/main/java/org/rumbledb/runtime/operational/base/BinaryOperationBaseIterator.java
  src/main/java/org/rumbledb/types/ItemType.java
  src/main/java/org/rumbledb/types/ItemTypes.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
  src/test/java/iq/FrontendTests.java
Labels: Approved

#518 Make enum private.
  src/main/java/org/rumbledb/types/ItemType.java
Labels: Approved

#520 Refactor2
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/logic/AndExpression.java
  src/main/java/org/rumbledb/expressions/logic/OrExpression.java
  src/main/java/org/rumbledb/expressions/operational/base/OperationalExpressionBase.java
  src/main/java/org/rumbledb/runtime/operational/AndOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/OrOperationIterator.java
Labels: Approved

#524 Two more iterators.
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/arithmetic/AdditiveExpression.java
  src/main/java/org/rumbledb/expressions/logic/AndExpression.java
  src/main/java/org/rumbledb/expressions/miscellaneous/StringConcatExpression.java
  src/main/java/org/rumbledb/expressions/operational/base/OperationalExpressionBase.java
  src/main/java/org/rumbledb/runtime/operational/AdditiveOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/MultiplicativeOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/StringConcatIterator.java
  src/main/java/org/rumbledb/runtime/operational/base/BinaryOperationBaseIterator.java
Labels: Approved

#523 Paralellized head function
  src/main/java/org/rumbledb/runtime/functions/sequences/general/HeadFunctionIterator.java
Labels: Approved

#527 Flatten multiplication.
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/arithmetic/MultiplicativeExpression.java
  src/main/java/org/rumbledb/expressions/operational/MultiplicativeExpression.java
  src/main/java/org/rumbledb/expressions/operational/base/NaryExpressionBase.java
  src/main/java/org/rumbledb/expressions/operational/base/OperationalExpressionBase.java
  src/main/java/org/rumbledb/expressions/postfix/DynamicFunctionCallExpression.java
  src/main/java/org/rumbledb/runtime/operational/MultiplicativeOperationIterator.java
Labels: Approved

#528 Fix comparison.
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/arithmetic/AdditiveExpression.java
  src/main/java/org/rumbledb/expressions/arithmetic/MultiplicativeExpression.java
  src/main/java/org/rumbledb/expressions/comparison/ComparisonExpression.java
  src/main/java/org/rumbledb/expressions/logic/AndExpression.java
  src/main/java/org/rumbledb/expressions/logic/OrExpression.java
  src/main/java/org/rumbledb/expressions/miscellaneous/RangeExpression.java
  src/main/java/org/rumbledb/expressions/miscellaneous/StringConcatExpression.java
  src/main/java/org/rumbledb/expressions/operational/ComparisonExpression.java
  src/main/java/org/rumbledb/expressions/operational/base/BinaryExpressionBase.java
  src/main/java/org/rumbledb/expressions/operational/base/OperationalExpressionBase.java
  src/main/java/org/rumbledb/items/ArrayItem.java
  src/main/java/org/rumbledb/items/Base64BinaryItem.java
  src/main/java/org/rumbledb/items/BooleanItem.java
  src/main/java/org/rumbledb/items/DateItem.java
  src/main/java/org/rumbledb/items/DateTimeItem.java
  src/main/java/org/rumbledb/items/DayTimeDurationItem.java
  src/main/java/org/rumbledb/items/DecimalItem.java
  src/main/java/org/rumbledb/items/DoubleItem.java
  src/main/java/org/rumbledb/items/DurationItem.java
  src/main/java/org/rumbledb/items/HexBinaryItem.java
  src/main/java/org/rumbledb/items/IntegerItem.java
  src/main/java/org/rumbledb/items/NullItem.java
  src/main/java/org/rumbledb/items/ObjectItem.java
  src/main/java/org/rumbledb/items/StringItem.java
  src/main/java/org/rumbledb/items/TimeItem.java
  src/main/java/org/rumbledb/items/YearMonthDurationItem.java
  src/main/java/org/rumbledb/runtime/operational/AdditiveOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/ComparisonOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/MultiplicativeOperationIterator.java
  src/main/java/org/rumbledb/runtime/operational/base/ComparisonUtil.java
  src/main/java/org/rumbledb/runtime/primary/StringRuntimeIterator.java
  src/main/java/org/rumbledb/runtime/typing/CastIterator.java
  src/main/java/sparksoniq/io/validation/OutputValidator.java
Labels: Approved

#529 Parallelized tail function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/TailFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionTail2.jq
Labels: Approved

#530 Add serialization for typeswitch.
  src/main/java/org/rumbledb/runtime/control/TypeswitchRuntimeIteratorCase.java
  src/main/resources/test_files/runtime-spark/Typeswitch.jq
Labels: Approved

#532 Fix rdd to DF conversion for arrays, add tests and data
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
  src/main/resources/queries/rumbleML/sample-ml-data-flat.json
  src/main/resources/queries/rumbleML/sample-ml-data-nested.json
  src/main/resources/queries/rumbleML/sample-ml-data-nested2.json
  src/main/resources/queries/rumbleML/sample-ml-data-nested3.json
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForPreprocessingLocalData1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateForPreprocessingRDDData1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-SchemaError1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-SchemaError2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-SchemaError3.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-SchemaError4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-TypeCasting1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD-TypeCasting2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD3.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD4.jq
  src/main/resources/test_files/runtime-spark/RumbleML/AnnotateFunction/MLAnnotateRDD5.jq
Labels: Approved

#535 Use annotate()ted item data (rdd or local) in existing ml tests
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-KMeans1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-LogisticRegression1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Binarizer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-Tokenizer1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/TransformerTests/MLTransformer-VectorAssembler1.jq
Labels: Approved, Refactoring

#538 Improvements with spotless and basedir usage in pom.xml
  pom.xml
Labels: Approved, Enhancement

#547 Fix SparkExceptions disappearing in Shell error handling
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/org/rumbledb/shell/RumbleJLineShell.java
Labels: Approved

#531 Parallelized one-or-more function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/cardinality/OneOrMoreIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMoreRDD1.disabled
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMoreRDD1.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMoreRDD2.jq
  src/main/resources/test_files/runtime/FunctionSequence/Cardinality/FunctionOneOrMoreRDDError1.jq
Labels: Approved

#526 Simplify itemType class and get rid of magic strings for types
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/items/FunctionItem.java
  src/main/java/org/rumbledb/items/KryoManager.java
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/OrderByClauseSparkIterator.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/OrderClauseCreateColumnsUDF.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/OrderClauseDetermineTypeUDF.java
  src/main/java/org/rumbledb/runtime/functions/FunctionItemCallIterator.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/types/ItemType.java
Labels: Approved, Refactoring

#555 Fix static context multipass for undefined function calls stored in variables
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/VisitorConfig.java
  src/main/java/org/rumbledb/compiler/VisitorHelpers.java
  src/main/java/org/rumbledb/expressions/CommaExpression.java
  src/main/java/org/rumbledb/expressions/Node.java
  src/main/java/org/rumbledb/expressions/comparison/ComparisonExpression.java
  src/main/java/org/rumbledb/expressions/flowr/Clause.java
  src/main/java/org/rumbledb/expressions/flowr/FlworExpression.java
  src/main/java/org/rumbledb/expressions/flowr/FlworVarDecl.java
  src/main/java/org/rumbledb/expressions/flowr/ForClause.java
  src/main/java/org/rumbledb/expressions/flowr/ForClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/LetClause.java
  src/main/java/org/rumbledb/expressions/flowr/LetClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/OrderByClauseExpr.java
  src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java
  src/main/java/org/rumbledb/expressions/postfix/ArrayLookupExpression.java
  src/main/java/org/rumbledb/expressions/postfix/ArrayUnboxingExpression.java
  src/main/java/org/rumbledb/expressions/postfix/ObjectLookupExpression.java
  src/main/java/org/rumbledb/expressions/postfix/PredicateExpression.java
  src/main/java/org/rumbledb/expressions/primary/FunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/primary/InlineFunctionExpression.java
  src/main/java/org/rumbledb/expressions/primary/VariableReferenceExpression.java
  src/main/java/org/rumbledb/expressions/typing/TreatExpression.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/resources/test_files/runtime/FunctionCall-UndefinedFunctionError1.jq
  src/main/resources/test_files/runtime/FunctionCall-UndefinedFunctionError2.jq
  src/main/resources/test_files/runtime/FunctionCall-UndefinedFunctionError3.jq
Labels: Approved, Bug

#542 Parallelized deep-equal function
  src/main/java/org/rumbledb/runtime/functions/sequences/value/DeepEqualFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/sequences/value/SameElementsAndLengthClosure.java
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual10.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual11.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionDeepEqual2.jq
Labels: Approved

#536 Update to format functionality for date and time functions
  docs/Function library.md
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatDateFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatDateTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatTimeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionFormatDateTime.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionFormatDate.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionFormatTime.jq
Labels: Approved

#558 Fix featuresCol param of RFormula estimator
  src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-RFormula.jq
  src/main/resources/test_files/runtime-spark/RumbleML/EstimatorTests/MLEstimator-RFormula.jq.disabled
Labels: Approved, RumbleML

#560 Some ml fixes
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
Labels: Approved, RumbleML

#564 Parallelized reverse function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/ReverseFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionReverse2.jq
Labels: Approved

#556 Cosmetic improvements to Functions.java
  src/main/java/org/rumbledb/compiler/VisitorHelpers.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
Labels: Approved

#565 Parallelized subseq function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/SubsequenceFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence11.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence12.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence13.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence14.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence15.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence16.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence17.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence18.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence19.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence20.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence21.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence22.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence23.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequence24.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError1.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError10.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError2.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError3.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError4.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError5.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError6.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError7.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError8.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionSubsequenceError9.jq
Labels: Approved

#569 Simplify for clause.
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/flowr/ForClause.java
  src/main/java/org/rumbledb/expressions/flowr/ForClauseVar.java
  src/main/java/org/rumbledb/expressions/postfix/DynamicFunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/primary/ArrayConstructorExpression.java
  src/main/java/org/rumbledb/expressions/primary/FunctionCallExpression.java
  src/main/java/sparksoniq/semantics/StaticContext.java
  src/main/resources/test_files/runtime-spark/DataFrames/ForClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/ForClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError1.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError2.jq
Labels: Approved

#563 Implement root reader.
  pom.xml
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/input/RootFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/postfix/ObjectLookupIterator.java
  src/main/java/org/rumbledb/shell/RumbleJLineShell.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/resources/queries/nested.json
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup4.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup5.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup6.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectLookup7.jq
Labels: Approved

#571 Updated tests for functions which already had parallelized implementations
  src/main/resources/test_files/runtime-spark/Pushdown/Empty.jq
  src/main/resources/test_files/runtime-spark/Pushdown/Exists.jq
  src/main/resources/test_files/runtime-spark/Pushdown/Head.jq
  src/main/resources/test_files/runtime-spark/Pushdown/IsEmpty.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionEmpty1.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionExists1.jq
Labels: Approved

#570 Implemented parallelized index-of function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/value/IndexOfFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/Value/ErrorFunctionIndexOf3.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/ErrorFunctionIndexOf4.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf10.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf11.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf12.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf6.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf7.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf8.jq
  src/main/resources/test_files/runtime/FunctionSequence/Value/FunctionIndexOf9.jq
Labels: Approved

#574 Implemented parallelized remove function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/RemoveFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove10.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove11.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove12.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove13.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove7.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove8.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemove9.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError1.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError2.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError3.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError4.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError5.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionRemoveError6.jq
Labels: Approved

#580 Apply formatting and import optimization for auto-generated files
  src/main/java/org/rumbledb/parser/JsoniqBaseVisitor.java
  src/main/java/org/rumbledb/parser/JsoniqLexer.java
  src/main/java/org/rumbledb/parser/JsoniqParser.java
  src/main/java/org/rumbledb/parser/JsoniqVisitor.java
Labels: Refactoring

#575 Support array unboxing for dataframes.
  src/main/java/org/rumbledb/runtime/postfix/ArrayUnboxingIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayUnboxing3.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayUnboxing4.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayUnboxing5.jq
Labels: Approved

#576 Add support for array lookup in DF.
  src/main/java/org/rumbledb/runtime/postfix/ArrayLookupIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup6.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup7.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayLookup8.jq
Labels: Approved

#577 Parallelization of remove-keys function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectRemoveKeysClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectRemoveKeysFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/RemoveKeys.jq
Labels: Approved

#557 Parallelize project function
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectProjectClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectProjectFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/Project.jq
Labels: Approved

#573 Let clause
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/flowr/Clause.java
  src/main/java/org/rumbledb/expressions/flowr/FlworExpression.java
  src/main/java/org/rumbledb/expressions/flowr/ForClause.java
  src/main/java/org/rumbledb/expressions/flowr/LetClause.java
  src/main/java/org/rumbledb/expressions/flowr/LetClauseVar.java
  src/main/resources/test_files/runtime-spark/DataFrames/LetClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/LocalClauses/LetClauseTypeCheckError.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError3.jq
  src/main/resources/test_files/runtime-spark/NestedFLWORSparkError4.jq
Labels: Approved

#585 Parallelize flatten function
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayFlattenClosure.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayFlattenFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayFlatten.jq
Labels: Approved

#583 Fix result of flatten function in documentation.
  docs/Function library.md
Labels: Approved

#578 Implemented insert-before parallelization
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/InsertBeforeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore10.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore11.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore12.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore13.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore14.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore15.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore16.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore17.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore18.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore19.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore20.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore21.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore22.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError1.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError2.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError3.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError4.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError5.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBeforeError6.jq
Labels: Approved

#582 Support DF for subsequence.
  src/main/java/org/rumbledb/runtime/functions/sequences/general/SubsequenceFunctionIterator.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/resources/test_files/runtime-spark/DataFrames/Subsequence1.jq
  src/main/resources/test_files/runtime-spark/DataFrames/Subsequence2.jq
  src/main/resources/test_files/runtime-spark/DataFrames/Subsequence3.jq
  src/main/resources/test_files/runtime-spark/DataFrames/Subsequence4.jq
Labels: Approved

#587 Now parallelized function when both inputs are rdds
  src/main/java/org/rumbledb/runtime/functions/sequences/general/InsertBeforeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore19.jq
  src/main/resources/test_files/runtime/FunctionSequence/General/FunctionInsertBefore23.jq
Labels: Approved

#590 Prevent silent failing of unhandled log paths
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
Labels: Approved

#586 Simplification and cleanup of quantified variables
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpression.java
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpressionVar.java
  src/main/java/org/rumbledb/runtime/postfix/ArrayUnboxingIterator.java
  src/main/java/org/rumbledb/runtime/quantifiers/QuantifiedExpressionIterator.java
Labels: Approved

#581 Increase Laurelin version to fix cache issue in root-file(),
  pom.xml
Labels: Approved

#598 Group by clean
  pom.xml
  src/main/java/org/rumbledb/api/Rumble.java
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/flowr/FlworVarDecl.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClause.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClauseVar.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByVariableDeclaration.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/GroupByClauseSparkIterator.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/OrderByClauseSparkIterator.java
  src/main/java/org/rumbledb/runtime/flwor/expression/GroupByClauseSparkIteratorExpression.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/GroupClauseCreateColumnsUDF.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/WhereClauseUDF.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/java/sparksoniq/semantics/StaticContext.java
  src/main/resources/test_files/runtime-spark/ErrorStackTrace.jq
  src/test/java/iq/RuntimeTests.java
Labels: Approved

#588 Fixed bug in anyURI related to kryo read/write
  src/main/java/org/rumbledb/items/AnyURIItem.java
  src/main/java/org/rumbledb/runtime/functions/sequences/general/InsertBeforeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURI1.jq
  src/main/resources/test_files/runtime/FunctionAnyURI/FunctionAnyURI2.jq
Labels: Approved

#592 Fix rumble parameters
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/org/rumbledb/config/RumbleRuntimeConfiguration.java
Labels: Approved

#601 Typeswitch fix2
  src/main/java/org/rumbledb/runtime/control/TypeswitchRuntimeIterator.java
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression6.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression7.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression8.jq
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpression9.jq
Labels: Approved

#604 Clean up URL validator and added allowed schemes
  src/main/java/org/rumbledb/runtime/functions/input/JsonFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/TextFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/UrlValidator.java
Labels: Approved

#605 Warning fix
  pom.xml
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpression.java
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpressionVar.java
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
Labels: Approved

#603 Clean up order by clause
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/flowr/OrderByClause.java
  src/main/java/org/rumbledb/expressions/flowr/OrderByClauseSortingKey.java
  src/main/java/org/rumbledb/runtime/flwor/expression/OrderByClauseAnnotatedChildIterator.java
  src/main/java/org/rumbledb/runtime/flwor/udfs/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKeyComparator.java
Labels: Approved

#606 Version1.5
  docs/Function library.md
  docs/Getting started.md
  docs/JSONiq.md
  docs/Run on a cluster.md
  docs/install.md
  mkdocs.yml
  src/main/resources/assets/banner.txt
Labels: Approved

#608 Fix access to other storage layers than HDFS.
  src/main/java/org/rumbledb/runtime/functions/input/JsonFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/TextFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/UrlValidator.java
Labels: Approved
