Repository RumbleDB/rumble, pull requests merged in 2020-04, with the labels that each got.

#610 Implemented serialization function
  docs/Function library.md
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/strings/SerializeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/SerializeFunction1.jq
  src/main/resources/test_files/runtime/FunctionString/SerializeFunction2.jq
  src/main/resources/test_files/runtime/FunctionString/SerializeFunction3.jq
  src/main/resources/test_files/runtime/FunctionString/SerializeFunction4.jq
  src/main/resources/test_files/runtime/FunctionString/SerializeFunctionError1.jq
  src/main/resources/test_files/runtime/FunctionString/SerializeFunctionError2.jq
Labels: Approved

#599 Prevent redundant vectorization
  src/main/java/sparksoniq/spark/ml/ApplyEstimatorRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
Labels: Approved

#611 Implemented avro function
  pom.xml
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/input/AvroFileFunctionIterator.java
  src/main/resources/queries/userdata.avsc
  src/main/resources/queries/userdata1-limit.avro
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFile1.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFile2.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFile3.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFile4.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError1.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError2.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError3.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError4.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError5.jq
  src/main/resources/test_files/runtime-spark/FileInputs/AvroFileError6.jq
  src/test/java/iq/RuntimeTests.java
Labels: Approved

#612 Added documentation entry for avro-file
  docs/Function library.md
Labels: Review Required

#609 Clean up cli
  pom.xml
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/org/rumbledb/runtime/functions/input/FileSystemUtil.java
  src/main/java/org/rumbledb/runtime/functions/input/JsonFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/TextFileFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/input/UrlValidator.java
  src/main/java/org/rumbledb/shell/RumbleJLineShell.java
  src/main/java/sparksoniq/utils/FileUtils.java
  src/main/java/sparksoniq/utils/Tuple.java
Labels: Approved

#614 Expression trees are now pretty-printed.
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/expressions/CommaExpression.java
  src/main/java/org/rumbledb/expressions/Node.java
  src/main/java/org/rumbledb/expressions/arithmetic/AdditiveExpression.java
  src/main/java/org/rumbledb/expressions/arithmetic/MultiplicativeExpression.java
  src/main/java/org/rumbledb/expressions/arithmetic/UnaryExpression.java
  src/main/java/org/rumbledb/expressions/comparison/ComparisonExpression.java
  src/main/java/org/rumbledb/expressions/control/ConditionalExpression.java
  src/main/java/org/rumbledb/expressions/control/SwitchExpression.java
  src/main/java/org/rumbledb/expressions/control/TypeSwitchExpression.java
  src/main/java/org/rumbledb/expressions/flowr/Clause.java
  src/main/java/org/rumbledb/expressions/flowr/CountClause.java
  src/main/java/org/rumbledb/expressions/flowr/FlworExpression.java
  src/main/java/org/rumbledb/expressions/flowr/ForClause.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClause.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByVariableDeclaration.java
  src/main/java/org/rumbledb/expressions/flowr/LetClause.java
  src/main/java/org/rumbledb/expressions/flowr/OrderByClause.java
  src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java
  src/main/java/org/rumbledb/expressions/flowr/WhereClause.java
  src/main/java/org/rumbledb/expressions/logic/AndExpression.java
  src/main/java/org/rumbledb/expressions/logic/NotExpression.java
  src/main/java/org/rumbledb/expressions/logic/OrExpression.java
  src/main/java/org/rumbledb/expressions/miscellaneous/RangeExpression.java
  src/main/java/org/rumbledb/expressions/miscellaneous/StringConcatExpression.java
  src/main/java/org/rumbledb/expressions/module/MainModule.java
  src/main/java/org/rumbledb/expressions/module/Prolog.java
  src/main/java/org/rumbledb/expressions/module/VariableDeclaration.java
  src/main/java/org/rumbledb/expressions/postfix/ArrayLookupExpression.java
  src/main/java/org/rumbledb/expressions/postfix/ArrayUnboxingExpression.java
  src/main/java/org/rumbledb/expressions/postfix/DynamicFunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/postfix/ObjectLookupExpression.java
  src/main/java/org/rumbledb/expressions/postfix/PredicateExpression.java
  src/main/java/org/rumbledb/expressions/primary/ArrayConstructorExpression.java
  src/main/java/org/rumbledb/expressions/primary/BooleanLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/ContextItemExpression.java
  src/main/java/org/rumbledb/expressions/primary/DecimalLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/DoubleLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/FunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/primary/InlineFunctionExpression.java
  src/main/java/org/rumbledb/expressions/primary/IntegerLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/NamedFunctionReferenceExpression.java
  src/main/java/org/rumbledb/expressions/primary/NullLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/ObjectConstructorExpression.java
  src/main/java/org/rumbledb/expressions/primary/StringLiteralExpression.java
  src/main/java/org/rumbledb/expressions/primary/VariableReferenceExpression.java
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpression.java
  src/main/java/org/rumbledb/expressions/quantifiers/QuantifiedExpressionVar.java
  src/main/java/org/rumbledb/expressions/typing/CastExpression.java
  src/main/java/org/rumbledb/expressions/typing/CastableExpression.java
  src/main/java/org/rumbledb/expressions/typing/InstanceOfExpression.java
  src/main/java/org/rumbledb/expressions/typing/TreatExpression.java
  src/main/java/org/rumbledb/runtime/RuntimeIterator.java
  src/main/java/org/rumbledb/runtime/RuntimeTupleIterator.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/jsoniq/ExecutionMode.java
  src/test/java/utils/AstSerialization.java
Labels: Approved

#617 Throw error if cannot materialize.
  docs/Error codes.md
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/config/RumbleRuntimeConfiguration.java
  src/main/java/org/rumbledb/context/DynamicContext.java
  src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
  src/main/java/org/rumbledb/exceptions/CannotMaterializeException.java
  src/main/java/org/rumbledb/runtime/HybridRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/resources/test_files/runtime-spark/MaterializationError.jq
  src/test/java/iq/RuntimeTests.java
  src/test/java/iq/SparkRuntimeTests.java
  src/test/java/iq/base/AnnotationsTestsBase.java
Labels: Approved, Changes Required

#622 Bump Spark version to 2.4.4
  pom.xml
Labels: Approved

#623 Display nicer error message if parsing error.
  src/main/java/org/rumbledb/items/parsing/ItemParser.java
Labels: Approved

#602 Implementation of parallel intersect function.
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectMapClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectReduceClosure.java
  src/main/resources/test_files/runtime-spark/Pushdown/Intersect.jq
Labels: Approved

#626 Parallelization of descendant-objects function.
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectDescendantClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectDescendantFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectDescendant.jq
Labels: Approved

#625 Parallelization of descendant-arrays function.
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayDescendantClosure.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayDescendantFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayDescendant.jq
Labels: Approved

#630 Arrow
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/parser/Jsoniq.g4
  src/main/java/org/rumbledb/parser/JsoniqBaseVisitor.java
  src/main/java/org/rumbledb/parser/JsoniqLexer.java
  src/main/java/org/rumbledb/parser/JsoniqParser.java
  src/main/java/org/rumbledb/parser/JsoniqVisitor.java
  src/main/resources/test_files/runtime/Arrow1.jq
  src/main/resources/test_files/runtime/Arrow2.jq
  src/main/resources/test_files/runtime/Arrow3.jq
  src/main/resources/test_files/runtime/Arrow4.jq
Labels: Approved, Changes Required

#627 Fix return clause parallel
  src/main/java/org/rumbledb/expressions/flowr/ReturnClause.java
  src/main/java/org/rumbledb/runtime/flwor/clauses/ReturnClauseSparkIterator.java
  src/main/java/sparksoniq/spark/DataFrameUtils.java
  src/main/resources/test_files/runtime-spark/ReturnDataFrame1.jq
  src/main/resources/test_files/runtime-spark/ReturnDataFrame2.jq
  src/main/resources/test_files/runtime-spark/ReturnRDD1.jq
  src/main/resources/test_files/runtime-spark/ReturnRDD2.jq
  src/main/resources/test_files/runtime-spark/ReturnRDD3.jq
Labels: Approved

#624 Simple map expression (local implementation)
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/expressions/AbstractNodeVisitor.java
  src/main/java/org/rumbledb/expressions/flowr/SimpleMapExpression.java
  src/main/java/org/rumbledb/parser/Jsoniq.g4
  src/main/java/org/rumbledb/parser/JsoniqParser.java
  src/main/java/org/rumbledb/runtime/flwor/expression/SimpleMapExpressionIterator.java
  src/main/resources/test_files/runtime/SimpleMapExpression1.jq
  src/main/resources/test_files/runtime/SimpleMapExpression10.jq
  src/main/resources/test_files/runtime/SimpleMapExpression2.jq
  src/main/resources/test_files/runtime/SimpleMapExpression3.jq
  src/main/resources/test_files/runtime/SimpleMapExpression4.jq
  src/main/resources/test_files/runtime/SimpleMapExpression5.jq
  src/main/resources/test_files/runtime/SimpleMapExpression6.jq
  src/main/resources/test_files/runtime/SimpleMapExpression7.jq
  src/main/resources/test_files/runtime/SimpleMapExpression8.jq
  src/main/resources/test_files/runtime/SimpleMapExpression9.jq
  src/main/resources/test_files/runtime/SimpleMapExpressionError1.jq
  src/main/resources/test_files/runtime/SimpleMapExpressionError2.jq
  src/main/resources/test_files/runtime/SimpleMapExpressionError3.jq
Labels: Approved

#638 Diff ofresearch project 1
  docs/Function library.md
  src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
  src/main/java/org/rumbledb/exceptions/ComponentSpecifierNotAvailableException.java
  src/main/java/org/rumbledb/exceptions/IncorrectSyntaxFormatDateTimeException.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayDescendantClosure.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayDescendantFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayFlattenClosure.java
  src/main/java/org/rumbledb/runtime/functions/arrays/ArrayFlattenFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentDateFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentDateTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/CurrentTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatDateFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatDateTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/datetime/FormatTimeFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectDescendantClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectDescendantFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectMapClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectIntersectReduceClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectProjectClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectProjectFunctionIterator.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectRemoveKeysClosure.java
  src/main/java/org/rumbledb/runtime/functions/object/ObjectRemoveKeysFunctionIterator.java
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayDescendant.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ArrayFlatten.jq
  src/main/resources/test_files/runtime-spark/Pushdown/Intersect.jq
  src/main/resources/test_files/runtime-spark/Pushdown/ObjectDescendant.jq
  src/main/resources/test_files/runtime-spark/Pushdown/Project.jq
  src/main/resources/test_files/runtime-spark/Pushdown/RemoveKeys.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTime.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTimeError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionCurrentDateTimeError2.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionFormatDateTime.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionFormatDateTimeError1.jq
  src/main/resources/test_files/runtime/FunctionDateTimes/FunctionFormatDateTimeError2.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDate.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDateError1.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionCurrentDateError2.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionFormatDate.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionFormatDateError1.jq
  src/main/resources/test_files/runtime/FunctionDates/FunctionFormatDateError2.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTime.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTimeError1.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionCurrentTimeError2.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionFormatTime.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionFormatTimeError1.jq
  src/main/resources/test_files/runtime/FunctionTimes/FunctionFormatTimeError2.jq
Labels: Approved

#634 Support for global variable declaration.
  docs/Error codes.md
  src/main/java/org/rumbledb/compiler/DynamicContextVisitor.java
  src/main/java/org/rumbledb/compiler/RuntimeIteratorVisitor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/TranslationVisitor.java
  src/main/java/org/rumbledb/context/StaticContext.java
  src/main/java/org/rumbledb/errorcodes/ErrorCodes.java
  src/main/java/org/rumbledb/exceptions/VariableAlreadyExistsException.java
  src/main/java/org/rumbledb/expressions/module/VariableDeclaration.java
  src/main/java/org/rumbledb/expressions/typing/TreatExpression.java
  src/main/java/org/rumbledb/runtime/RuntimeIterator.java
  src/main/resources/test_files/runtime/VariableDeclaration1.jq
  src/main/resources/test_files/runtime/VariableDeclaration2.jq
  src/main/resources/test_files/runtime/VariableDeclaration4.jq
  src/main/resources/test_files/runtime/VariableDeclaration5.jq
  src/main/resources/test_files/runtime/VariableDeclaration6.jq
  src/main/resources/test_files/runtime/VariableDeclaration7.jq
  src/main/resources/test_files/runtime/VariableDeclarationError1.jq
  src/main/resources/test_files/runtime/VariableDeclarationError2.jq
  src/main/resources/test_files/runtime/VariableDeclarationError3.jq
  src/main/resources/test_files/runtime/VariableDeclarationError4.jq
  src/test/java/iq/RuntimeTests.java
  src/test/java/iq/base/AnnotationsTestsBase.java
Labels: Approved, Changes Required

#645 Parallelization of conditional expression
  src/main/java/org/rumbledb/expressions/control/ConditionalExpression.java
  src/main/java/org/rumbledb/runtime/control/IfRuntimeIterator.java
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDIfExpr.jq
Labels: Approved

#646 Parallelization of switch expression
  src/main/java/org/rumbledb/expressions/control/SwitchExpression.java
  src/main/java/org/rumbledb/runtime/control/SwitchRuntimeIterator.java
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDSwitchExpression.jq
Labels: Approved
