Repository RumbleDB/rumble, pull requests merged in 2020-01, with the labels that each got.

#420 Fix bug.
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/resources/test_files/runtime-spark/DataFrames/GroupbyClause18.jq
Labels: Approved

#422 Empty sequence if
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/IfRuntimeIterator.java
  src/main/resources/test_files/runtime/ControlIterators/IfExpr12.jq
  src/main/resources/test_files/runtime/ControlIterators/IfExpr13.jq
  src/main/resources/test_files/runtime/ControlIterators/IfExpr14.jq
Labels: Approved

#424 Cherry pick.
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/sparksoniq/jsoniq/item/ItemComparatorForSequences.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworKey.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/java/sparksoniq/spark/SparkSessionManager.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/test/java/iq/RuntimeTests.java
Labels: Approved

#426 Cherry pick.
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
Labels: Approved

#427 1- Convert dynamic function call iterator to local
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/DynamicFunctionCallIterator.java
Labels: Approved

#428 2-Remove spark runtime iterator
  src/main/java/sparksoniq/jsoniq/runtime/iterator/SparkRuntimeIterator.java
Labels: Approved

#429 3-Cleanup var refs and for let clauses
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RDDRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/quantifiers/QuantifiedExpressionIterator.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/ReturnClauseSparkIterator.java
Labels: Approved

#430 4-Cleanup function item call iterator
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
Labels: Approved, Priority

#432 6-Add previous clause to flwor expressions
  src/main/java/sparksoniq/jsoniq/compiler/JsoniqExpressionTreeVisitor.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/FlworClause.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/ForClause.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/LetClause.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/postfix/extensions/PostfixExtension.java
Labels: Approved

#433 7-Improve static context
  src/main/java/sparksoniq/semantics/StaticContext.java
Labels: Approved

#434 8-Fix is rdd usage in Hybrid Runtime Iterator
  src/main/java/sparksoniq/jsoniq/runtime/iterator/HybridRuntimeIterator.java
Labels: Approved, On hold, Priority

#436 9-Correctly cleanup UDFs between each test run
  src/test/java/iq/base/AnnotationsTestsBase.java
Labels: Approved

#435 10 - Cosmetic improvements for StaticIsRDD
  .travis.yml
  src/main/java/sparksoniq/jsoniq/runtime/iterator/CommaExpressionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/SwitchRuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/BuiltinFunction.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/operational/RangeOperationIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ObjectConstructorRuntimeIterator.java
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/GroupByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/LetClauseSparkIterator.java
Labels: Approved

#437 11-Materialize function
  src/main/java/sparksoniq/jsoniq/runtime/iterator/RuntimeIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectAccumulateFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectIntersectFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectProjectFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/object/ObjectRemoveKeysFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/AvgFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/CountFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/MaxFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/MinFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/aggregate/SumFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/general/ReverseFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/sequences/value/DeepEqualFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/strings/StringJoinFunctionIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/postfix/PredicateIterator.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/ArrayRuntimeIterator.java
Labels: Approved

#440 11-2-Cleanup static context visitor
  src/main/java/sparksoniq/semantics/visitor/AbstractExpressionOrClauseVisitor.java
  src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
Labels: Approved

#438 12-Support RDD and DF in functionItem closures
  src/main/java/sparksoniq/jsoniq/item/FunctionItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/FunctionItemCallIterator.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
Labels: Approved

#423 Rumble ml - Implement getting and running transformers
  docs/Error codes.md
  pom.xml
  src/main/java/sparksoniq/exceptions/InvalidRumbleMLParamException.java
  src/main/java/sparksoniq/exceptions/UnrecognizedRumbleMLClassReferenceException.java
  src/main/java/sparksoniq/exceptions/UnrecognizedRumbleMLParamReferenceException.java
  src/main/java/sparksoniq/exceptions/codes/ErrorCodes.java
  src/main/java/sparksoniq/jsoniq/item/FunctionItem.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/functions/base/Functions.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
  src/main/java/sparksoniq/spark/ml/GetTransformerFunctionIterator.java
  src/main/java/sparksoniq/spark/ml/RumbleMLCatalog.java
  src/main/java/sparksoniq/spark/ml/RumbleMLUtils.java
  src/main/resources/queries/rumbleML/sample-ml-numeric-data.json
  src/main/resources/queries/rumbleML/sample-ml-string-data.json
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformerErrorIllegalArgument1.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformerErrorIllegalArgument2.jq
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformerMultiple1.jq.disabled
  src/main/resources/test_files/runtime-spark/RumbleML/MLTransformerTokenizer1.jq
Labels: Approved, RumbleML

#441 12-2-Add static type checking for typeswitch default case
  src/main/java/sparksoniq/semantics/visitor/StaticContextVisitor.java
  src/main/resources/test_files/runtime/ControlIterators/TypeswitchExpressionError2.jq
Labels: Approved

#442 13-2-Fix order by clause expr
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/ExpressionOrClause.java
  src/main/java/sparksoniq/jsoniq/compiler/translator/expr/flowr/OrderByClauseExpr.java
Labels: Approved

#448 Simplify typeSwitchExpression by removing redundant variableReferenceIterators
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchCase.java
  src/main/java/sparksoniq/jsoniq/runtime/iterator/control/TypeSwitchRuntimeIterator.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
Labels: Approved

#446 Rename DF to dataFrame in Flwor tuple and dynamic context
  src/main/java/sparksoniq/jsoniq/runtime/iterator/primary/VariableReferenceIterator.java
  src/main/java/sparksoniq/jsoniq/tuple/FlworTuple.java
  src/main/java/sparksoniq/semantics/DynamicContext.java
  src/main/java/sparksoniq/spark/iterator/flowr/ForClauseSparkIterator.java
  src/main/java/sparksoniq/spark/ml/ApplyTransformerRuntimeIterator.java
Labels: Approved

#447 Improve naming of orderbyClauseSparkIteratorExpression and its usage
  src/main/java/sparksoniq/jsoniq/tuple/FlworKeyComparator.java
  src/main/java/sparksoniq/semantics/visitor/RuntimeIteratorVisitor.java
  src/main/java/sparksoniq/spark/iterator/flowr/OrderByClauseSparkIterator.java
  src/main/java/sparksoniq/spark/iterator/flowr/expression/OrderByClauseAnnotatedChildIterator.java
  src/main/java/sparksoniq/spark/udf/OrderClauseCreateColumnsUDF.java
  src/main/java/sparksoniq/spark/udf/OrderClauseDetermineTypeUDF.java
  src/test/java/iq/FrontendTests.java
Labels: Approved, Priority
