Repository RumbleDB/rumble, pull requests merged in 2020-05, with the labels that each got.

#653 Implement colored outputs
  src/main/java/org/rumbledb/shell/ANSIColor.java
  src/main/java/org/rumbledb/shell/RumbleJLineShell.java
Labels: Approved

#655 Improve getGroupProjectSQL
  src/main/java/org/rumbledb/runtime/flwor/FlworDataFrameUtils.java
Labels: Approved, Refactoring

#644 Updated parallelization of comma expression
  src/main/java/org/rumbledb/expressions/CommaExpression.java
  src/main/java/org/rumbledb/runtime/CommaExpressionIterator.java
  src/main/resources/test_files/runtime-spark/RDDComma.jq
Labels: Approved

#660 Server
  server_tests_manual.txt
  src/main/java/org/rumbledb/api/Item.java
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/cli/Main.java
  src/main/java/org/rumbledb/config/RumbleRuntimeConfiguration.java
  src/main/java/org/rumbledb/expressions/module/FunctionDeclaration.java
  src/main/java/org/rumbledb/items/ArrayItem.java
  src/main/java/org/rumbledb/items/ObjectItem.java
  src/main/java/org/rumbledb/server/RumbleHttpHandler.java
  src/main/java/org/rumbledb/server/RumbleServer.java
  src/main/java/org/rumbledb/shell/RumbleJLineShell.java
Labels: Approved, Changes Required

#662 Cleanup request validation in RumbleHttpHandler
  src/main/java/org/rumbledb/server/RumbleHttpHandler.java
Labels: Approved

#656 Parallelized simple map expression
  src/main/java/org/rumbledb/expressions/flowr/SimpleMapExpression.java
  src/main/java/org/rumbledb/runtime/flwor/expression/SimpleMapExpressionClosure.java
  src/main/java/org/rumbledb/runtime/flwor/expression/SimpleMapExpressionIterator.java
  src/main/resources/test_files/runtime/SimpleMapExpression11.jq
  src/main/resources/test_files/runtime/SimpleMapExpression12.jq
  src/main/resources/test_files/runtime/SimpleMapExpression13.jq
  src/main/resources/test_files/runtime/SimpleMapExpression14.jq
  src/main/resources/test_files/runtime/SimpleMapExpression15.jq
  src/main/resources/test_files/runtime/SimpleMapExpression16.jq
  src/main/resources/test_files/runtime/SimpleMapExpression17.jq
  src/main/resources/test_files/runtime/SimpleMapExpression18.jq
  src/main/resources/test_files/runtime/SimpleMapExpression19.jq
  src/main/resources/test_files/runtime/SimpleMapExpression20.jq
Labels: Approved

#658 Parallelization of typeswitch expression
  src/main/java/org/rumbledb/expressions/control/TypeSwitchExpression.java
  src/main/java/org/rumbledb/runtime/control/TypeswitchRuntimeIterator.java
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDTypeswitchExpression1.jq
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDTypeswitchExpression2.jq
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDTypeswitchExpression3.jq
  src/main/resources/test_files/runtime-spark/ControlIterators/RDDTypeswitchExpression4.jq
Labels: Approved

#671 Add RumbleML Documentation
  docs/RumbleML.md
Labels: Review Required, RumbleML

#676 Implemented normalize-unicode function
  docs/Function library.md
  src/main/java/org/rumbledb/errorcodes/ErrorCode.java
  src/main/java/org/rumbledb/exceptions/InvalidNormalizationException.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/java/org/rumbledb/runtime/functions/strings/NormalizeUnicodeFunctionIterator.java
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicode1.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicode2.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicode3.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicode4.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicodeError1.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicodeError2.jq
  src/main/resources/test_files/runtime/FunctionString/NormalizeUnicodeError3.jq
Labels: Approved

#678 Register parameter execution modes.
  src/main/java/org/rumbledb/api/Rumble.java
  src/main/java/org/rumbledb/cli/JsoniqQueryExecutor.java
  src/main/java/org/rumbledb/compiler/StaticContextVisitor.java
  src/main/java/org/rumbledb/compiler/VariableDependenciesVisitor.java
  src/main/java/org/rumbledb/compiler/VisitorConfig.java
  src/main/java/org/rumbledb/compiler/VisitorHelpers.java
  src/main/java/org/rumbledb/expressions/Node.java
  src/main/java/org/rumbledb/expressions/flowr/FlworExpression.java
  src/main/java/org/rumbledb/expressions/flowr/GroupByClause.java
  src/main/java/org/rumbledb/expressions/module/FunctionDeclaration.java
  src/main/java/org/rumbledb/expressions/primary/FunctionCallExpression.java
  src/main/java/org/rumbledb/expressions/primary/InlineFunctionExpression.java
  src/main/java/org/rumbledb/runtime/functions/base/Functions.java
  src/main/resources/test_files/runtime-spark/UserDefinedFunctions/UserDefinedFunction1.jq
  src/main/resources/test_files/runtime-spark/UserDefinedFunctions/UserDefinedFunction2.jq
  src/main/resources/test_files/runtime-spark/UserDefinedFunctions/UserDefinedFunction3.jq
  src/main/resources/test_files/runtime-spark/UserDefinedFunctions/UserDefinedFunction4.jq
  src/test/java/iq/base/AnnotationsTestsBase.java
Labels: Approved
